CREATE OR REPLACE FUNCTION handle_raid_attack(
    p_room_uuid UUID,
    p_profile_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_room RECORD;
    v_player RECORD;
    v_map RECORD;
    v_participants_count INT;
    v_player_damage INT;
    v_new_boss_hp INT;
    v_boss_damage INT;
    v_new_player_hp INT;
    v_alive_participants_count INT;
    v_next_turn INT;
BEGIN
    -- Get room, player, and map details
    SELECT * INTO v_room FROM public.raid_rooms WHERE room_uuid = p_room_uuid;
    SELECT * INTO v_player FROM public.raid_participants WHERE room_id = v_room.id AND profile_id = p_profile_id;
    SELECT * INTO v_map FROM public.raid_maps WHERE id = v_room.map_id;
    SELECT COUNT(*) INTO v_participants_count FROM public.raid_participants WHERE room_id = v_room.id AND is_alive = TRUE;

    -- Prevent division by zero if no one is alive
    IF v_participants_count = 0 THEN
        RETURN jsonb_build_object('success', false, 'message', 'No players are alive.');
    END IF;

    -- Validate turn
    IF (v_room.current_turn % v_participants_count) != (v_player.slot_number - 1) THEN
        RETURN jsonb_build_object('success', false, 'message', 'Not your turn.');
    END IF;

    -- Player attacks boss
    SELECT strength INTO v_player_damage FROM public.profiles WHERE id = p_profile_id;
    v_new_boss_hp := GREATEST(0, COALESCE(v_room.boss_hp, 0) - v_player_damage);

    UPDATE public.raid_rooms SET boss_hp = v_new_boss_hp WHERE id = v_room.id;

    -- Check if boss is defeated
    IF v_new_boss_hp <= 0 THEN
        IF v_room.current_round < 3 THEN
            -- Go to next round
            UPDATE public.raid_rooms
            SET current_round = v_room.current_round + 1,
                current_turn = 0,
                boss_hp = NULL, -- Will be regenerated by client
                boss_max_hp = NULL
            WHERE id = v_room.id;
        ELSE
            -- Raid complete (victory)
            UPDATE public.raid_rooms SET status = 'completed' WHERE id = v_room.id;
        END IF;
    ELSE
        -- Boss attacks player
        v_boss_damage := (SELECT (CASE v_map.difficulty_level 
                                    WHEN 1 THEN 25 WHEN 2 THEN 35 ELSE 50 END) * (1 + (v_map.difficulty_level - 1) * 0.5));
        v_new_player_hp := GREATEST(0, v_player.current_hp - v_boss_damage);

        UPDATE public.raid_participants
        SET current_hp = v_new_player_hp,
            is_alive = (v_new_player_hp > 0)
        WHERE id = v_player.id;

        -- Check if all players are defeated
        SELECT COUNT(*) INTO v_alive_participants_count FROM public.raid_participants WHERE room_id = v_room.id AND is_alive = TRUE;
        IF v_alive_participants_count = 0 THEN
            UPDATE public.raid_rooms SET status = 'completed' WHERE id = v_room.id;
        ELSE
            -- Advance to next turn
            v_next_turn := (v_room.current_turn + 1);
            UPDATE public.raid_rooms SET current_turn = v_next_turn WHERE id = v_room.id;
        END IF;
    END IF;

    RETURN jsonb_build_object('success', true, 'message', 'Attack handled.');
END;
$$;
